[package]
name = "chessai"
version = "0.1.10"
edition = "2024"
authors = ["atopx <3940422@qq.com>"]
repository = "https://github.com/atopx/chessai.git"
description = "a chiness chess ai"
license = "MIT"

[dependencies]
rand = "0.9"
